flanes/urls.py
from django.urls import path, include
from flanes import views

urlpatterns = [
    path('about_flans/', views.about_flans, name="about_flans"),
    path('welcome_flans/', views.welcome_flans, name="welcome_flans"),
    path('contact_flans/', views.contact_flans, name="contact_flans"),
    path('success_flans/', views.success_flans, name="success_flans"),
    path('index_flans/', views.index_flans, name="index_flans"),
    path('accounts_flans/', include("django.contrib.auth.urls")),
    path('flan/<int:flan_id>',views.flan_detail, name="flan_detail"),
    path('add_to_cart/<int:flan_id>/', views.add_to_cart, name='add_to_cart'),
    path('view_cart/', views.view_cart, name='view_cart'),
    path('remove_from_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

muebles/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from portfolio import settings
from muebles import views

urlpatterns = [
    path('index_muebles', views.index_muebles, name='index_muebles'),
    path('register_muebles/', views.register_muebles, name="register_muebles"),
    path('login_muebles/', LoginView.as_view(template_name='login_muebles.html'), name='login_muebles'),
    path('logout_muebles/', LogoutView.as_view(next_page='index_muebles'), name='logout_muebles'),
    path('inmueble/<int:id>/', views.detalle_inmueble, name='detalle_inmueble'),
    path('solicitud_arriendo/<int:id>', views.solicitud_arriendo, name='solicitud_arriendo'),
    path('usuario_muebles/<int:user_id>/', views.usuario_muebles, name='usuario_muebles'),
    path('editar_perfil/<int:user_id>', views.editar_perfil, name='editar_perfil'),
    path('inmuebles/<int:user_id>/', views.inmuebles_especificos, name='inmuebles_especificos'),
    path('inmuebles_all/', views.inmuebles_all, name='inmuebles_all'),
    path('agregar_inmueble/<int:user_id>', views.agregar_inmueble, name='agregar_inmueble'),
    path('mueble_subido', views.mueble_subido, name='mueble_subido'),
    path('editar_inmueble/<int:id>/<int:user_id>/', views.editar_inmueble, name='editar_inmueble'),
    path('borrar_inmueble/<int:id>/', views.borrar_inmueble, name='borrar_inmueble'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('contacto/', views.contacto, name='contacto'),
    path('success/', views.succes, name='success'),
    path('formacion/', views.formacion, name='formacion'),
    path('informacion/', views.informacion, name='informacion'),
    path('competencias/', views.competencias, name='competencias'),
    path('onlyflans/', include('flanes.urls')),
    path('muebles/', include('muebles.urls')),
    path('viajes_chile/', include('viajes_chile.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

muebles/models.py
from django.db import models
from django.contrib.auth.models import User

class Region(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
class Comuna(models.Model):
    nombre = models.CharField(max_length=100)
    region = models.ForeignKey(Region, related_name='comunas', on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Usuario(User):
    TIPO_USUARIO_CHOISES = [
        ('arrendatario', 'Arrendatario'),
        ('arrendador', 'Arrendador'),
    ]
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    rut = models.CharField(max_length=10, unique=True)
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=13)
    tipo_usuario = models.CharField(max_length=20, choices=TIPO_USUARIO_CHOISES)
    correo_electronico = models.EmailField(unique=True, default='correo@correo.cl') 

    def __str__(self):
        return f"{self.nombres} {self.apellidos}"
        
class Inmueble(models.Model):
    TIPO_INMUEBLE_CHOISES = [
        ('casa','Casa'),
        ('departamento','Departamento'),
        ('parcela','Parcela'),
    ]
    nombre=models.CharField(max_length=50)
    direccion=models.CharField(max_length=50)
    descripcion=models.CharField(max_length=50)
    imagen =models.ImageField(upload_to='',null=True, blank=True)
    precio=models.DecimalField(max_digits=10, decimal_places=0)
    comuna = models.ForeignKey(Comuna, related_name='inmuebles', on_delete=models.CASCADE)
    disponible=models.BooleanField(default=True)
    m2_construidos = models.DecimalField(max_digits=10, decimal_places=2)
    m2_terreno = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad_estacionamientos = models.PositiveIntegerField()
    cantidad_habitaciones = models.PositiveIntegerField()
    cantidad_banos = models.PositiveIntegerField()
    tipo_de_inmueble=models.CharField(max_length=12, choices=TIPO_INMUEBLE_CHOISES)
    propietario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return f"{self.nombre}"
    
class SolicitudArriendo(models.Model):
    TIPO_ESTADO_CHOISES = [
        ('pendiente','Pendiente'),
        ('aceptado','Aceptado'),
        ('rechazado','Rechazado'),   
    ]
     
    arrendatario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    inmueble = models.ForeignKey(Inmueble, on_delete=models.CASCADE)
    mensaje = models.TextField(blank=True)
    estado =models.CharField(choices=TIPO_ESTADO_CHOISES, default='pendiente',max_length=100)
    
    def __str__(self):
        return f"Solicitud de {self.inmueble.nombre} por {self.arrendatario.nombres} {self.arrendatario.apellidos}"    

muebles/forms.py
from django import forms
from .models import Usuario, Inmueble

class RegistroUsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['username', 'password', 'nombres', 'apellidos', 'rut', 'direccion', 'telefono', 'correo_electronico', 'tipo_usuario']
        widgets = {
            'password': forms.PasswordInput(),
        }

class EdicionPerfilForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['username', 'nombres', 'apellidos', 'rut', 'direccion', 'telefono', 'correo_electronico', 'tipo_usuario']
        widgets = {
            'password': forms.PasswordInput(render_value=True),
        }

        def clean_username(self):
            username = self.cleaned_data.get('username')
            return username
        
class InmuebleForm(forms.ModelForm):
    class Meta:
        model = Inmueble
        fields = '__all__'

muebles/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required

from muebles.models import SolicitudArriendo, Inmueble, Usuario, Comuna
from .forms import RegistroUsuarioForm, EdicionPerfilForm, InmuebleForm

def index_muebles(request):
    return render(request, 'index_muebles.html')

def inmuebles_all(request):
    inmubles = Inmueble.objects.all()
    return render(request, 'inmuebles_all.html', {'inmuebles':inmubles})

@login_required
def detalle_inmueble(request, id):
    inmueble = Inmueble.objects.get(pk=id)
    return render(request, 'detalle_inmueble.html', {'inmueble': inmueble})

def register_muebles(request):
    if request.method == 'POST':
        form = RegistroUsuarioForm(request.POST)
        if form.is_valid():
            usuario = form.save(commit=False)
            password = form.cleaned_data['password']
            usuario.set_password(password)
            usuario.save()
            usuario_autenticado = authenticate(username=usuario.username, password=password)
            if usuario_autenticado is not None:
                login(request, usuario_autenticado)
                return redirect('index_muebles')  
    else:
        form = RegistroUsuarioForm()
    return render(request, 'register_muebles.html', {'form': form})

@login_required
def solicitud_arriendo(request, id):
    inmueble = get_object_or_404(Inmueble, pk=id)
    
    if request.user.is_authenticated and request.user.usuario.tipo_usuario == 'arrendatario':
        if request.method == 'POST':
            form = SolicitudArriendo(request.POST)
            if form.is_valid():
                solicitud = form.save(commit=False)
                solicitud.arrendatario = request.user.usuario
                solicitud.inmueble = inmueble
                solicitud.save()
                return redirect('detalle', id=inmueble.id)
        else:
            form = SolicitudArriendo(initial={'inmueble': inmueble})
        return render(request, 'generar_solicitud_arriendo.html', {'form': form})
    else:
        return redirect('index_muebles')

@login_required
def usuario_muebles(request, user_id):
    try:
        usuario = Usuario.objects.get(id=user_id)
    except Usuario.DoesNotExist:
        if user_id == 1:
            messages.warning(request, "Problemas especificos con usuario admin, use otro.")
            return redirect('index_muebles')
        messages.warning(request, "El usuario no existe")
        return redirect('index_muebles')
    
    return render(request, 'usuario_muebles.html', {'usuario': usuario})

def editar_perfil(request, user_id):
    usuario = get_object_or_404(Usuario, id=user_id)

    if request.method == 'POST':
        formulario = EdicionPerfilForm(request.POST, instance=usuario)
        if formulario.is_valid():
            formulario.save()
            return redirect('usuario_muebles', user_id=user_id)
    else:
        formulario = EdicionPerfilForm(instance=usuario)

    return render(request, 'editar_perfil.html', {'formulario': formulario, 'usuario': usuario})

@login_required
def inmuebles_especificos(request, user_id):
    usuario = get_object_or_404(Usuario, id=user_id)
    inmuebles = Inmueble.objects.filter(propietario=usuario)

    return render(request, 'inmuebles.html', {'inmuebles': inmuebles})

@login_required
def agregar_inmueble(request, user_id):
    comunas = Comuna.objects.all()
    usuario = get_object_or_404(Usuario, id=user_id)

    if request.method == 'POST':
        form = InmuebleForm(request.POST, request.FILES)
        if form.is_valid():
            inmueble = form.save(commit=False)
            inmueble.propietario = usuario
            if 'imagen' in request.FILES:
                inmueble.imagen = request.FILES['imagen']
                inmueble.save()
                return redirect('mueble_subido') 
            else:
                form = InmuebleForm()
    else:
        form = InmuebleForm()
    
    return render(request, 'agregar_inmueble.html', {'form': form, 'comunas': comunas, 'usuario': usuario})


def mueble_subido(request):
    return render(request, 'mueble_subido.html')

@login_required
def editar_inmueble(request, id, user_id):
    inmueble = get_object_or_404(Inmueble, pk=id)
    usuario = get_object_or_404(Usuario, pk=user_id)

    if usuario.tipo_usuario == "arrendatario":
        if user_id == inmueble.propietario_id:
            if request.method == 'POST':
                form = InmuebleForm(request.POST, request.FILES, instance=inmueble)
                if form.is_valid():
                    inmueble = form.save(commit=False)
                    inmueble.propietario = usuario
                    if 'imagen' in request.FILES:
                        inmueble.imagen = request.FILES['imagen']
                    inmueble.save()
                    return redirect('detalle_inmueble', id=inmueble.id)
            else:
                form = InmuebleForm(instance=inmueble)

            return render(request, 'editar_inmueble.html', {'form': form, 'inmueble': inmueble})
        else:
            messages.warning(request, "Solo los dueños del inmueble pueden editarlo.")
            return redirect('index_muebles')
    else:
        messages.warning(request, "Solo los dueños del inmueble pueden editarlo.")
        return redirect('index_muebles')
    
def borrar_inmueble(request, id):
    inmueble = get_object_or_404(Inmueble, pk=id)
    inmueble.delete()
    return redirect('index_muebles') 

muebles/templates/agregar_inmueble.html
{% extends 'base_muebles.html' %}

{% block 'content' %}
<div class="container">
    <h2>Agregar inmueble</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_nombre">Nombre:</label>
            <input type="text" class="form-control" id="id_nombre" name="nombre" required>
        </div>
        <div class="form-group">
            <label for="id_direccion">Dirección:</label>
            <input type="text" class="form-control" id="id_direccion" name="direccion" required>
        </div>
        <div class="form-group">
            <label for="id_descripcion">Descripción:</label>
            <input type="text" class="form-control" id="id_descripcion" name="descripcion" required>
        </div>
        <p></p>
        <div class="form-group">
            <label for="id_imagen">Imagen:</label>
            <input type="file" class="form-control-file" id="id_imagen" name="imagen">
        </div>
        <p></p>
        <div class="form-group">
            <label for="id_precio">Precio:</label>
            <input type="number" class="form-control" id="id_precio" name="precio" required>
        </div>
        <div class="form-group">
            <label for="id_comuna">Comuna:</label>
            <select class="form-control" id="id_comuna" name="comuna" required>
                {% for comuna in comunas %}
                <option value="{{ comuna.id }}">{{ comuna.nombre }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="id_m2_construidos">Metros cuadrados construidos:</label>
            <input type="number" class="form-control" id="id_m2_construidos" name="m2_construidos" required>
        </div>
        <div class="form-group">
            <label for="id_m2_terreno">Metros cuadrados terreno:</label>
            <input type="number" class="form-control" id="id_m2_terreno" name="m2_terreno" required>
        </div>
        <div class="form-group">
            <label for="id_cantidad_estacionamientos">Cantidad de estacionamientos:</label>
            <input type="number" class="form-control" id="id_cantidad_estacionamientos" name="cantidad_estacionamientos" required>
        </div>
        <div class="form-group">
            <label for="id_cantidad_habitaciones">Cantidad de habitaciones:</label>
            <input type="number" class="form-control" id="id_cantidad_habitaciones" name="cantidad_habitaciones" required>
        </div>
        <div class="form-group">
            <label for="id_cantidad_banos">Cantidad de baños:</label>
            <input type="number" class="form-control" id="id_cantidad_banos" name="cantidad_banos" required>
        </div>
        <div class="form-group">
            <label for="id_tipo_inmueble">Tipo de Inmueble:</label>
            <select class="form-control" id="id_tipo_inmueble" name="tipo_de_inmueble" required>
                <option value="">Seleccione el tipo de inmueble</option>
                <option value="casa">Casa</option>
                <option value="departamento">Departamento</option>
                <option value="parcela">Parcela</option>
            </select>
        </div>
        <div class="form-group">
            <label for="id_disponible">Disponible:</label>
            <input type="checkbox" class="form-check-input" id="id_disponible" name="disponible">
        </div>
        <input type="hidden" name="propietario" value="{{usuario.id}}">
        <p></p>
        <button type="submit" class="btn btn-primary">Agregar</button>
    </form>
</div>
{% endblock %}

muebles/templates/base_muebles.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Bienvenido a Hito 1{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        body {
            background-color: #e8f5e9; /* Verde claro */
        }
        .navbar {
            background-color: #1b5e20; /* Verde oscuro */
        }
        .navbar-brand, .nav-link {
            color: #ffffff !important;
        }
        footer {
            background-color: #004d40; /* Verde azulado */
            color: #ffffff;
        }
    </style>
</head>
<body class="text-center">
    {% block 'header' %}
        
    {% endblock %}
        
    {% block 'navbar' %}
    <div class="container-fluid" style="background-color: #1b5e20;"> <!-- Verde oscuro -->
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Tu Sitio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'index_muebles' %}">Inicio</a>
                        </li>
                        {% if user.usuario.tipo_usuario == "arrendatario" %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'inmuebles_all' %}">inmuebles disponibles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'inmuebles_especificos' user.id %}">Panel arrendador</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'agregar_inmueble' user.id %}">Agregar inmueble</a>
                        </li>
                        {% elif user.usuario.tipo_usuario == "arrendador" %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'inmuebles_especificos' user.id %}">Panel arrendador</a>
                        </li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link d-inline" href="{% url 'usuario_muebles' user.id %}">bienvenido {{ user.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-inline" href="{% url 'logout_muebles' %}">Cerrar sesión</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login_muebles' %}">Iniciar sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register_muebles' %}">Registro</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    {% endblock %}
    {% block 'content' %}
    {% endblock %}
    {% block 'footer' %}
    <footer class="text-center text-white" style="background-color: #004d40; margin-top: 20px;"> <!-- Verde azulado -->
        <div class="container">
            <section class="mt-0">
                <div class="row text-center d-flex justify-content-center pt-5">
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                            <a href="{% url 'index' %}" class="text-white">Inicio</a>
                        </h6>
                    </div>
                </div>
            </section>
        </div>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            © 2024 Copyright:
        </div>
    </footer>
    {% endblock %}
    {% block 'javascript' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- Agrega más scripts JavaScript según sea necesario -->
    {% endblock %}
</body>
</html>

muebles/templates/detalle_inmueble.html
{% extends 'base_muebles.html' %}

{% block 'content' %}
{% csrf_token %}
    <div class="container" style="margin-top: 20px;">
        <div class="row">
            <div class="container-fluid col-md-4">
                <img src="//media/{{ inmueble.imagen }}" class="img-fluid card-img-top" alt="...">

            </div>
            <div class="col-md-4 mx-auto align-content-center" style="text-align: left;">
                <h2>{{ inmueble.nombre }}</h2>
                <p>{{ inmueble.descripcion }}</p>
                <p><strong>Precio: </strong> ${{ inmueble.precio }}</p>
                <p><strong>Comuna: </strong> {{ inmueble.comuna }}</p>
                <p><strong>Disponible: </strong> {{ inmueble.disponible }}</p>
                <p><strong>Metros cuadrados construidos: </strong> {{ inmueble.m2_construidos }}</p>
                <p><strong>Metro cuadrados totales: </strong> {{ inmueble.m2_terreno }}</p>
                <p><strong>Cantidad de estacionamientos: </strong> {{ inmueble.cantidad_estacionamientos }}</p>
                <p><strong>Cantidad de habitaciones: </strong> {{ inmueble.cantidad_habitaciones }}</p>
                <p><strong>Cantidad de baños: </strong> {{ inmueble.cantidad_banos }}</p>
                <p><strong>Tipo de inmueble: </strong> {{ inmueble.tipo_de_inmueble }}</p>
                <p><strong>Propietario: </strong> {{ inmueble.propietario }}</p>
                {% comment %} <a href={% url "solicitud_arriendo" inmueble.id %} class="btn btn-primary">Solicitud de arriendo</a> {% endcomment %}
                <a href="{% url 'index_muebles' %}" class="btn btn-primary">Volver a la pagina principal</a>
                <p></p>
                <a href={% url "editar_inmueble" inmueble.id user.usuario.id %} class="btn btn-primary">Editar inmueble</a>
            </div>
        </div>
    </div>
{% endblock %}

muebles/templates/editar_inmueble.html
{% extends 'base.html' %}

{% block 'content' %}
    <h1 class="text-center">Editar Perfil</h1>
    <div class="container" style="margin-top: 20px;">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                    <a href="{% url 'detalle_inmueble' inmueble.id %}" class="btn btn-secondary">Cancelar</a>
                </form>
                <form method="post" action="{% url 'borrar_inmueble' inmueble.id %}" style="margin-top: 20px;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que deseas eliminar este inmueble?');">Borrar inmueble</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

muebles/templates/editar_perfil.html
{% extends 'base_muebles.html' %}

{% block 'content' %}
    <h1 class="text-center">Editar Perfil</h1>
    <div class="container" style="margin-top: 20px;">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ formulario.as_p }}
                    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                    <a href="{% url 'index_muebles' %}" class="btn btn-secondary">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

muebles/templates/index_muebles.html
{% extends 'base_muebles.html' %}

{% block 'content' %}
<div class="container mt-5">
    {% if messages %}
        <div class="alert alert-warning">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <h1 class="mb-3">Página Principal</h1>
    <p>Bienvenido a nuestro sitio de arriendo de inmuebles. Aquí podrás encontrar una amplia selección de propiedades disponibles para arrendar, debes registrarte o iniciar sesión para poder ver los inmuebles por temas de seguridad</p>
</div>
{% endblock %}

{% block 'title' %}
    Bienvenido a desafio hito 1
{% endblock %}

muebles/templates/inmuebles.html
{% extends 'base_muebles.html' %}

{% block 'content' %}
<h1 class="text-center">Mis inmuebles</h1>
<div class="container">
    <div class="row">
{% for inm in inmuebles %}
        
        {% if inm.disponible == True %}
        <div class="col-sm-3">
            <img src="//media/{{inm.imagen}}" class="img-fluid card-img-top" alt="...">
            <h5 class="card-title">{{inm.nombre}}</h5>
            <p class="card-text">{{inm.descripcion}}</p>
            <a href={% url "detalle_inmueble" inm.id %} class="btn btn-primary">Disponible</a>
            <br><br>
        </div>
        {% elif inm.disponible == False %}
        <div class="col-sm-3">
            <img src="//media/{{inm.imagen}}" class="img-fluid card-img-top" alt="...">
            <h5 class="card-title">{{inm.nombre}}</h5>
            <p class="card-text">{{inm.descripcion}}</p>
            <a href={% url "detalle_inmueble" inm.id %} class="btn btn-secondary">Arrendado</a>
            <br><br>
        </div>
        {% endif %}
            

{% endfor %}
    </div>
</div>
{% endblock %}

{% block 'title'%}
    Bienvenido a desafio hito 1
{% endblock %}

muebles/templates/mueble_subido.html
{% extends 'base_muebles.html' %}

{% block 'content' %}
<div class="container mt-5">
    <h1 class="mb-3">Mueble subido con exito</h1>
</div>
{% endblock %}

{% block 'title'%}
    Mueble subido
{% endblock %}

muebles/templates/register_muebles.html
{% extends 'base_muebles.html' %}

{% block 'title' %}Página de Inicio{% endblock %}

{% block 'content' %}  
<div class="container">
    <h2>Registrarse</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Username:</label>
            <input type="text" class="form-control" id="id_username" name="username" required>
        </div>
        <div class="form-group">
            <label for="id_password">Password:</label>
            <input type="password" class="form-control" id="id_password" name="password" required>
        </div>
        <div class="form-group">
            <label for="id_nombres">Nombres:</label>
            <input type="text" class="form-control" id="id_nombres" name="nombres" required>
        </div>
        <div class="form-group">
            <label for="id_apellidos">Apellidos:</label>
            <input type="text" class="form-control" id="id_apellidos" name="apellidos" required>
        </div>
        <div class="form-group">
            <label for="id_rut">Rut:</label>
            <input type="text" class="form-control" id="id_rut" name="rut" required>
        </div>
        <div class="form-group">
            <label for="id_direccion">Direccion:</label>
            <input type="text" class="form-control" id="id_direccion" name="direccion" required>
        </div>
        <div class="form-group">
            <label for="id_telefono">Telefono:</label>
            <input type="tel" class="form-control" id="id_telefono" name="telefono" required>
        </div>
        <div class="form-group">
            <label for="id_correo_electronico">Correo electrónico:</label>
            <input type="email" class="form-control" id="id_correo_electronico" name="correo_electronico" required>
        </div>
        <div class="form-group">
            <label for="id_tipo_usuario">Tipo usuario:</label>
            <select class="form-control" id="id_tipo_usuario" name="tipo_usuario" required>
                <option value="arrendatario">Arrendatario</option>
                <option value="arrendador">Arrendador</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Registrarse</button>
    </form>
</div>
{% endblock %}

muebles/templates/solicitud_arriendo.html
{% extends 'base_muebles.html' %}

{% block title %}Página de Inicio{% endblock %}
{% load static %}
{% block content %}
<h1>Generar Solicitud de Arriendo</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar Solicitud</button>
</form>
{% endblock %}